### DISCUSSION TITLE
What are reasons that no valid configuration found when running motion_gen

### DISCUSSION THREAD

**Discussion by BolunDai0216** [NVlabs/curobo#121] [Software Q&A] [answered]
Hi,

I was trying to plan a path, but I keep getting

```bash
LBFGS: history >= d_opt, reducing history to d_opt-1
no valid configuration found
no valid configuration found
no valid configuration found
```

Is this because the IK failed or some other reason. The result dictionary looks like this

```bash
MotionGenResult(success=tensor([False], device='cuda:0'), valid_query=True, optimized_plan=None, optimized_dt=None, position_error=None, rotation_error=None, cspace_error=None, solve_time=0.012544870376586914, ik_time=0.012544870376586914, graph_time=0.0, trajopt_time=0.0, finetune_time=0.0, total_time=0.014700651168823242, interpolated_plan=None, interpolation_dt=0.02, path_buffer_last_tstep=None, debug_info=None, status='IK Fail', attempts=2, trajopt_attempts=0, used_graph=False, graph_plan=None)
```

Thanks in advance!

**Comment by balakumar-s** [comment]
result.status says that IK failed so the pose might not be reachable in a collision-free configuration

**Reply by BolunDai0216** [reply]
@balakumar-s Thanks for the response! I noticed that the inverse kinematics solver cannot find a solution even when the collision is not considered, which is a bit weird. For IK, since I first sampled a joint configuration and then computed its FK, a solution would exist, e.g.,

```bash
q_sample = ik_solver.sample_configs(1)
kin_state = ik_solver.fk(q_sample)
goal = Pose(kin_state.ee_position, kin_state.ee_quaternion)
result = ik_solver.solve_batch(goal)
```

Do you know what might be the issue? For your reference, the `.yml` file I am using looks like the following, is there something that looks wrong? I omitted some of the collision spheres since they are not used (probably?). 

```yaml
robot_cfg:
    kinematics:
        use_usd_kinematics: False
        usd_path: "/path/to/robot.usd"
        usd_robot_root: "/robot"
        isaac_usd_path: ""
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "/path/to/robot.urdf"
        asset_root_path: "/path/to/asset"

        base_link: "base"
        ee_link: "link_sucction_cup_tcp"
        link_names: null
        lock_joints: null
        extra_links: null


        collision_link_names: [base, link1, link2, link3, link4, link5, link_sucction_cup] # List[str]
        collision_spheres:
            base:
                - "center": [-0.055, 0.009, 0.391]
                  "radius": 0.599
            link1:
                - "center": [-0.0, -0.032, -0.011]
                  "radius": 0.195
            link2:
                - "center": [-0.014, -0.278, 0.003]
                  "radius": 0.185
            link3:
                - "center": [0.086, 0.001, 0.001]
                  "radius": 0.164
            link4:
                - "center": [0.715, -0.016, -0.0]
                  "radius": 0.15
            link5:
                - "center": [0.011, 0.007, 0.0]
                  "radius": 0.147
            link_sucction_cup:
                - "center": [0.065, -0.041, -0.075]
                  "radius": 0.129

        collision_sphere_buffer: 0.005
        extra_collision_spheres: {}
        self_collision_ignore: {
            "base": ["link1"],
            "link1": ["link2"],
            "link2": ["link3"],
            "link3": ["link4", "link5", "link_sucction_cup"],
            "link4": ["link5"],
            "link5": ["link_sucction_cup"],
        } # Dict[str, List[str]]
        self_collision_buffer: {
            "base": 0.01,
            "link1": 0.01,
            "link2": 0.01,
            "link3": 0.01,
            "link4": 0.01,
            "link5": 0.01,
            "link_sucction_cup": 0.01,
        } # Dict[str, float]

        use_global_cumul: True
        mesh_link_names: null # List[str]

        cspace:
            joint_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"] # List[str]
            retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
            null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
            cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
            max_jerk: 500.0
            max_acceleration: 15.0
```

The code I am using for inverse kinematics is

```python
tensor_args = TensorDeviceType()
robot_file ="path/to/robot.yml"
config_file = load_yaml(robot_file)
urdf_file = config_file["robot_cfg"]["kinematics"]["urdf_path"]
base_link = config_file["robot_cfg"]["kinematics"]["base_link"]
ee_link = config_file["robot_cfg"]["kinematics"]["ee_link"]
robot_cfg = RobotConfig.from_basic(urdf_file, base_link, ee_link, tensor_args)

ik_config = IKSolverConfig.load_from_robot_config(
    robot_cfg,
    None,
    rotation_threshold=0.3,
    position_threshold=0.05,
    num_seeds=500,
    self_collision_check=False,
    self_collision_opt=False,
    tensor_args=tensor_args,
    use_cuda_graph=True,
)
ik_solver = IKSolver(ik_config)
q_sample = ik_solver.sample_configs(1)
kin_state = ik_solver.fk(q_sample)
goal = Pose(kin_state.ee_position, kin_state.ee_quaternion)
result = ik_solver.solve_batch(goal)
```

**Reply by balakumar-s** [reply]
What's the output of result here?

**Reply by BolunDai0216** [reply]
The result looks like:

```bash
IKResult(js_solution=JointState(position=tensor([[[ 0.0795,  1.0095,  0.0762,  0.0998, -0.4300,  0.3723]]],
       device='cuda:0'), velocity=None, acceleration=None, joint_names=['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6'], jerk=None, tensor_args=TensorDeviceType(device=device(type='cuda', index=0), dtype=torch.float32)), goal_pose=Pose(position=tensor([[ 1.4184, -0.1386,  0.8862]], device='cuda:0'), quaternion=tensor([[ 0.3781,  0.0436, -0.8639, -0.3298]], device='cuda:0'), rotation=None, batch=1, n_goalset=1, name='ee_link', normalize_rotation=True), solution=tensor([[[ 0.0795,  1.0095,  0.0762,  0.0998, -0.4300,  0.3723]]],
       device='cuda:0'), seed=None, success=tensor([[False]], device='cuda:0'), position_error=tensor([[0.1286]], device='cuda:0'), rotation_error=tensor([[0.9526]], device='cuda:0'), error=tensor([[1.0811]], device='cuda:0'), solve_time=1.2829647064208984, debug_info={'solver': {'steps': [[], []], 'cost': [[], []]}})

```

**Reply by balakumar-s** [reply]
Since you are using a batch size of 1, can you try solve_single? Or increase the batch size to 2.

**Reply by BolunDai0216** [reply]
@balakumar-s If I do 

```python
q_sample = ik_solver.sample_configs(1)
kin_state = ik_solver.fk(q_sample)
goal = Pose(kin_state.ee_position, kin_state.ee_quaternion)
result = ik_solver.solve_single(goal)
```

The result looks like

```bash
IKResult(js_solution=JointState(position=tensor([[[ 0.0795,  1.0095,  0.0762,  0.0998, -0.4300,  0.3723]]],
       device='cuda:0'), velocity=None, acceleration=None, joint_names=['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6'], jerk=None, tensor_args=TensorDeviceType(device=device(type='cuda', index=0), dtype=torch.float32)), goal_pose=Pose(position=tensor([[ 1.4184, -0.1386,  0.8862]], device='cuda:0'), quaternion=tensor([[ 0.3781,  0.0436, -0.8639, -0.3298]], device='cuda:0'), rotation=None, batch=1, n_goalset=1, name='ee_link', normalize_rotation=True), solution=tensor([[[ 0.0795,  1.0095,  0.0762,  0.0998, -0.4300,  0.3723]]],
       device='cuda:0'), seed=None, success=tensor([[False]], device='cuda:0'), position_error=tensor([[0.1286]], device='cuda:0'), rotation_error=tensor([[0.9526]], device='cuda:0'), error=tensor([[1.0811]], device='cuda:0'), solve_time=1.3052949905395508, debug_info={'solver': {'steps': [[], []], 'cost': [[], []]}})
```

If I increase the batch size to 2 like this

```python
q_sample = ik_solver.sample_configs(2)
kin_state = ik_solver.fk(q_sample)
goal = Pose(kin_state.ee_position, kin_state.ee_quaternion)
result = ik_solver.solve_batch(goal)
```

The result looks like this

```bash
IKResult(js_solution=JointState(position=tensor([[[ 0.0795,  1.0095,  0.0762,  0.0998, -0.4300,  0.3723]],

        [[ 1.8911, -0.3537,  0.3571, -2.5356,  0.8395, -0.1614]]],
       device='cuda:0'), velocity=None, acceleration=None, joint_names=['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6'], jerk=None, tensor_args=TensorDeviceType(device=device(type='cuda', index=0), dtype=torch.float32)), goal_pose=Pose(position=tensor([[ 1.4184, -0.1386,  0.8862],
        [-0.1939,  0.5403,  2.4146]], device='cuda:0'), quaternion=tensor([[ 0.3781,  0.0436, -0.8639, -0.3298],
        [ 0.1056,  0.7359,  0.6655,  0.0667]], device='cuda:0'), rotation=None, batch=2, n_goalset=1, name='ee_link', normalize_rotation=True), solution=tensor([[[ 0.0795,  1.0095,  0.0762,  0.0998, -0.4300,  0.3723]],

        [[ 1.8911, -0.3537,  0.3571, -2.5356,  0.8395, -0.1614]]],
       device='cuda:0'), seed=None, success=tensor([[False],
        [ True]], device='cuda:0'), position_error=tensor([[0.1286],
        [0.0013]], device='cuda:0'), rotation_error=tensor([[0.9526],
        [0.0212]], device='cuda:0'), error=tensor([[1.0811],
        [0.0225]], device='cuda:0'), solve_time=1.3052008152008057, debug_info={'solver': {'steps': [[], []], 'cost': [[], []]}})
```

Looks like one of them in the second case succeeded. If I change the batch size to 5, the success tensor looks like this:

```bash
tensor([[False],
        [ True],
        [False],
        [ True],
        [False]], device='cuda:0')
```

Is this the expected behavior?

**Reply by BolunDai0216** [reply]
@balakumar-s I tried running the same code but with the provided `franka.yml`, and it can solve IK for all of the randomly sampled joint configurations. So I suspect the issue is with the robot configuration file. I included the robot configuration file above, do you think anything is missing that might cause this issue, or is there anything that I need to be careful about in URDF that might cause this issue? I was also trying to do some more debugging, but I did not find where the IK solver is implemented, is it in Python or given as a binary?

**Reply by BolunDai0216** [reply]
@balakumar-s I tested a few other robot models, now I suspect maybe it's the robot's fault. I see that for UR10e, the IK solver success rate drops dramatically to around 50%. I am using a CRX10iA (which like UR10e has 6 actuated joints and a similar topology), so maybe the issue is with the robot's kinematics. Do you think that might be the case?

**Reply by balakumar-s** [reply]
It looks like the very first time when you call `result = ik_solver.solve_batch(goal)`, the success rate is low but calling it after that gives close to 100% success rate, even with UR10e. Can you try and confirm?

**Reply by BolunDai0216** [reply]
@balakumar-s That is indeed the case! Why does this happen?

However, when I try to run the motion planner twice for my robot like this

```python
motion_gen_config = MotionGenConfig.load_from_robot_config(
      robot_file,
      world_file,
      tensor_args,
      interpolation_dt=0.1,
)
motion_gen = MotionGen(motion_gen_config)
motion_gen.warmup(enable_graph=True)

robot_cfg = load_yaml(join_path(get_robot_configs_path(), robot_file))["robot_cfg"]
robot_cfg = RobotConfig.from_dict(robot_cfg, tensor_args)
retract_cfg = motion_gen.get_retract_config()

state = motion_gen.rollout_fn.compute_kinematics(JointState.from_position(retract_cfg.view(1, -1)))
retract_pose = Pose(state.ee_pos_seq.squeeze(), quaternion=state.ee_quat_seq.squeeze())
start_state = JointState.from_position(retract_cfg.view(1, -1) + 0.3)
result = motion_gen.plan_single(
    start_state, retract_pose, MotionGenPlanConfig(max_attempts=5, enable_graph=False, enable_graph_attempt=None, enable_opt=True)
)
result = motion_gen.plan_single(
    start_state, retract_pose, MotionGenPlanConfig(max_attempts=5, enable_graph=False, enable_graph_attempt=None, enable_opt=True)
)
```

I still cannot get a solution. Do you know what might be the issue here? For your reference, `result` looks like this

```bash
MotionGenResult(success=tensor([False], device='cuda:0'), valid_query=True, optimized_plan=None, optimized_dt=None, position_error=None, rotation_error=None, cspace_error=None, solve_time=0.02951812744140625, ik_time=0.02951812744140625, graph_time=0.0, trajopt_time=0.0, finetune_time=0.0, total_time=0.03362774848937988, interpolated_plan=None, interpolation_dt=0.02, path_buffer_last_tstep=None, debug_info=None, status='IK Fail', attempts=5, trajopt_attempts=0, used_graph=False, graph_plan=None)
```

If I change the `MotionGenPlanConfig` to `MotionGenPlanConfig(max_attempts=5)` it also fails to find a solution. Since the status is `IK Fail` is it related to the inverse kinematics problem mentioned above? However, for UR10e, it does not have this same problem with the motion generator.

**Reply by BolunDai0216** [reply]
@balakumar-s I also noticed that it gives me

```bash
no valid configuration found
no valid configuration found
no valid configuration found
```

when running:

```python
motion_gen.warmup(enable_graph=True)
```

do you know what that indicates?

**Reply by balakumar-s** [reply]
It might be because of not setting self collision parameters correctly. Can you try motion gen with:

```
motion_gen_config = MotionGenConfig.load_from_robot_config(
      robot_file,
      world_file,
      tensor_args,
      interpolation_dt=0.1,
     self_collision_check=False,
     self_collision_opt=False
)
```

If it still doesn't work, set world_file = None. If it works than, there is something incorrect in the robot configuration file.

**Reply by BolunDai0216** [reply]
Yes, this works! What does this imply?

**Reply by balakumar-s** [reply]
If this works, then your robot is in self collision at the retract_cfg:

` retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]`

Can you change this:

```
self_collision_ignore: {
            "base": ["link1"],
            "link1": ["link2"],
            "link2": ["link3"],
            "link3": ["link4", "link5", "link_sucction_cup"],
            "link4": ["link5"],
            "link5": ["link_sucction_cup"],
        } 
```
to 
```
self_collision_ignore: {
            "base": ["link1"],
            "link1": ["link2"],
            "link2": ["link3"],
            "link3": ["link4", "link5", "link_sucction_cup"],
            "link4": ["link5", "link_suction_cup"],
            "link5": ["link_sucction_cup"],
        } 
```

and see if that works?  Also set `self_collision_check=True, self_collision_opt=True`.

**Reply by BolunDai0216** [reply]
@balakumar-s Thanks for looking into this. After playing around with it I found that this gave me successful results

```yaml
self_collision_ignore: {
    "base": ["link1", "link2"],
    "link1": ["link2"],
    "link2": ["link3", "link4"],
    "link3": ["link4", "link5", "link_sucction_cup"],
    "link4": ["link5", "link_sucction_cup"],
    "link5": ["link_sucction_cup"],
}
```

However, I think this is different from what I see in the Isaac sim editor. Also, I noticed that when I was playing around with the `self_collision_ignore`, I sometimes got this output

```bash
skip 13
skip 14
skip 15
skip 16
skip 17
skip 18
skip 19
skip 20
LBFGS: history >= d_opt, reducing history to d_opt-1
skip 13
skip 14
skip 15
skip 16
skip 17
skip 18
skip 19
skip 20
```

Do you know what this means?
