### DISCUSSION TITLE
Integrating a Custom Welding Torch (STEP) as End-Effector for Collision Modeling

### DISCUSSION THREAD

**Discussion by patrick-deschambault** [NVlabs/curobo#521] [Research Q&A]
Hi,

First of all, thank you for the fantastic work on CuRobo it's a very promising library. I'm currently a research master's student working on collision-free path planning for autonomous robotic welding, and CuRobo has really caught my attention for its potential in manufacturing applications.

As part of my work, I need to integrate a custom end-effector, specifically a welding torch, which I currently have as a .step file. Ultimately, I would like to model the torch for collision detection, ideally using the sphere-based approximation method suggested on the [robot configuration tutorial](https://curobo.org/tutorials/1_robot_configuration.html).

I was wondering:

- Is it possible to integrate a custom tool like this into a CuRobo robot configuration?

- If so, is there a recommended workflow or best practices to follow for converting and approximating the tool geometry using collision spheres? 

I really appreciate any guidance or examples you could share.

Thanks again!

Patrick

**Comment by KySmith1** [comment]
This is definitely possible. We do this today and can see the results in simulation. I'm writing this from memory, but IIRC the big steps are:

1. **STLs and Kinematics:** For visual acknowledgement with tools like `UsdHelper.write_trajectory_animation`, place your end effector STL in an accessible directory. Reference the model in your URDF as a mesh like so:
```
    <!-- End Effector Attachments Below this Line -->
    <link name="end_effector">
        <visual>
            <origin rpy="-1.5707963267948966 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="/path/to/suction_end_effector.STL"/>
            </geometry>
            <material name="LightGrey">
                <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="wrist_3-end_effector" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="wrist_3_link"/>
        <child link="end_effector"/>
    </joint>
    <!-- End Effector Virtual Attach Point -->
    <!-- 2mm Sphere to denote the CuRobo target pose -->
    <link name="end_effector_attach_point">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="/path/to/end_effector_attachment_point.STL"/>
            </geometry>
            <material name="Red">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="end_effector_attach_point_joint" type="fixed">
        <!-- Sphere must be offset by +1mm from the end effector Z+ axis to be centered -->
        <!-- E.g. An end effector with a Z offset of 0.149m would have a z value of 0.148m -->
        <origin rpy="0 0 0" xyz="0 0 0.163" />
        <parent link="end_effector"/>
        <child link="end_effector_attach_point"/>
    </joint>
```
As always, define the `origin` relative to the final wrist link. This STL is only your visual guide and won't define any collision spheres within the environment (more on that later). Defining the origin is actually the most important component here since it will inform the kinematic chain.

As we have done, you should consider adding a visual indicator as to the welding arc point to help you out down the line. This "attach point" will also be referenced later.

2. **Collision Spheres and More Kinematics**
Every instantiation of a `MotionGen` object should also come along with loading a configuration:
```
    motion_gen_configuration = path.join(
        "path", "to", "your", "motion_config.yaml"
    )
    ...
    motion_gen_cfg = MotionGenConfig.load_from_robot_config(
        motion_gen_configuration,
        "collision_table.yml",
        tensor_args,
        trajopt_tsteps=34,
        ...
        (many different kwargs set below)
    )
```
The motion gen configuration (as we call it anyway) [should look like one of these](https://github.com/NVlabs/curobo/tree/main/src/curobo/content/configs/robot). Couple of key points:
```
ee_link: "end_effector_attach_point"
```
You should define your final end effector point here. This will serve as your target pose when you call something like `plan_single`.
```
    mesh_link_names:  ['base_link_inertia', 'shoulder_link','upper_arm_link', 'forearm_link', 'wrist_1_link',
    'wrist_2_link' ,'wrist_3_link', 'end_effector', 'end_effector_attach_point'] # List[str]
```
Add your chosen links to the mesh link names so they show up as STLs in the debug animations.
```
    collision_spheres:
      shoulder_link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.1
      ...
      end_effector:
        - "center": [ 0.0, 0.0, 0.02 ]
          "radius": 0.03
        - "center": [0.0, 0.0, 0.06]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.095 ]
          "radius": 0.035
        - "center": [ 0.0187, 0.0, 0.1325 ]
          "radius": 0.015
        - "center": [ 0.00935, 0.01619, 0.1325 ]
          "radius": 0.015
        - "center": [ -0.00935, 0.01619, 0.1325 ]
          "radius": 0.015
        - "center": [ -0.0187, 0.0, 0.1325 ]
          "radius": 0.015
        - "center": [ -0.00935, -0.01619, 0.1325 ]
          "radius": 0.015
        - "center": [ 0.00935, -0.01619, 0.1325 ]
          "radius": 0.015
  ```
  And now we come to the collision spheres. You're going to have to define them manually with respect to their appropriate link. You can probably come up with a few in CAD as a first shot, but we found it essentially required to use the output of `UsdHelper.write_trajectory_animation` as a source of truth when we were doing tight motions. You might not have to if you don't have a complex collision environment.
  
 ```
     self_collision_ignore: {
      "shoulder_link": [],
      "upper_arm_link": ["forearm_link", "shoulder_link"],
      "forearm_link": ["wrist_1_link", "wrist_2_link"],
      "wrist_1_link": ["wrist_2_link", "wrist_3_link"],
      "wrist_2_link": ["wrist_1_link", "wrist_3_link"],
      "wrist_3_link": ["end_effector", "attached_object"],
      }
 ```
 Now that you have your end effector attached, make sure to have CuRobo ignore `wrist_3_link` as it'll be consistently in collision most likely.
 
 Happy to reply more on this thread if you get stuck. Like I said, we have what you're after currently after on live robots.
