### ISSUE TITLE
"qx, qy, qz, qw" or "qw, qx, qy, qz"

### ISSUE THREAD

**Issue by Cfather** [NVlabs/curobo#226]
In "collision_base.yml", it said:
```
cuboid:
  table:
    dims: [0.1, 0.1, 0.8] # x, y, z
    pose: [0.0, 0.0, -0.45, 1, 0, 0, 0.0] # x, y, z, qw, qx, qy, qz
```
While in "collision_table.yml", it said:
```
cuboid:
  table:
    dims: [5.0, 5.0, 0.2] # x, y, z
    pose: [0.0, 0.0, -0.1, 1, 0, 0, 0.0] # x, y, z, qx, qy, qz, qw
```
I wonder which one is true?
