### ISSUE TITLE
IK Solver fails for planar movement robot

### ISSUE THREAD

**Issue by MarcoGrabowski** [NVlabs/curobo#493]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]): Python
2. python version: 3.10.16
3. Isaac Sim version (if using): No Isaac Sim
------
Issue Details

I want to run a minimal example of a planar robot, where I just calculate a trajectory from a start to an end pose without obstacles. But that fails. 

I've used the given example code files and modified it for my purpose. My robot consists of 3 prismatic joints (for x, y and z) and no rotation. I even disabled all collisions checking flags I could find. But on evaluating the trajectoy, I get "IK failed". So I broke it down to only calculating the IK for the goal pose, which trivially consists of x, y and z because of the 3 orthogonal prismatic joints. The goal pose is clearly within the reachable range of the prismatic joints. But the IK Solver fails.

Can anyone confirm, this is a bug?

The code to reproduce:

#### `motion_example.py`
``` python
# Third Party
import torch

# cuRobo
from curobo.types.math import Pose
from curobo.types.robot import JointState
from curobo.wrap.reacher.motion_gen import MotionGen, MotionGenConfig, MotionGenPlanConfig

motion_gen_config = MotionGenConfig.load_from_robot_config(
    "xplanar_mover.yml",
    None, # No obstacles
    interpolation_dt=0.01,
    self_collision_check=False,
    self_collision_opt = False,
)

motion_gen = MotionGen(motion_gen_config)
motion_gen.warmup()

goal_pose = Pose.from_list([15, 15, 1.0])  # x, y, z

start_state = JointState.from_position(
    torch.zeros(1, 3).cuda(),
    joint_names=[
        "base_to_height_joint",
        "height_to_tile_x_joint", 
        "tile_x_to_tile_y_joint"
    ],
)

ik_result = motion_gen.solve_ik(goal_pose=goal_pose)
print(">>> IK Result Success: ", ik_result.success) # Returns false
print(">>> IK Result: ", ik_result)

result = motion_gen.plan_single(start_state, goal_pose, MotionGenPlanConfig(max_attempts=1))

print(">>> Trajectory Generated: ", result.success) # Returns false, too (IK failed)
``` 

#### `xplanar_mover.urdf (located at assets/robot/xplanar/)` 
``` urdf
<?xml version="1.0"?>
<robot name="planar_tile_mover">

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>
    </collision> -->
  </link>

  <!-- Intermediate link used solely for x-axis translation -->
  <link name="height_link">
    <!-- No visual or collision elements are needed because this link serves as a transformation frame -->
  </link>

    <!-- Intermediate link used solely for x-axis translation -->
  <link name="tile_x_link">
    <!-- No visual or collision elements are needed because this link serves as a transformation frame -->
  </link>

  <!-- Tile link representing the moving tile part -->
  <link name="tile_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1"/>
      </material>
    </visual>
    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>
    </collision> -->
  </link>

  <!-- Prismatic joint for z-axis translation -->
  <joint name="base_to_height_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="height_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100.0" lower="-100.0" upper="100.0" velocity="1.0"/>
  </joint>  
  
  <!-- Prismatic joint for x-axis translation -->
  <joint name="height_to_tile_x_joint" type="prismatic">
    <parent link="height_link"/>
    <child link="tile_x_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="100.0" lower="-100.0" upper="100.0" velocity="1.0"/>
  </joint>

  <!-- Prismatic joint for y-axis translation -->
  <joint name="tile_x_to_tile_y_joint" type="prismatic">
    <parent link="tile_x_link"/>
    <child link="tile_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100.0" lower="-100.0" upper="100.0" velocity="1.0"/>
  </joint>
</robot>
```

#### `xplanar_mover.yml (located at configs/robot/`
```yml
robot_cfg:
  kinematics:
    use_usd_kinematics: False
    # usd_path: "robot/xplanar/xplanar_mover.usd"
    usd_robot_root: "/robot/"
    isaac_usd_path: null
    urdf_path: "robot/xplanar/xplanar_mover.urdf"
    # asset_root_path: "/media/local/mgrabowski/curobo/src/curobo/content/assets/robot/xplanar"
    base_link: "base_link"
    ee_link: "tile_link"
    
    collision_link_names: null
    self_collision_ignore: ["base_link", "height_link", "tile_x_link", "tile_link"]
    collision_spheres: null
    collision_sphere_buffer: null #0.004 # 0.0025
    extra_collision_spheres: null
    use_global_cumul: True
    self_collision_ignore: True

    self_collision_buffer: null
    lock_joints: null                   # No joints to lock for a simple planar mover

    link_names: ["base_link", "height_link", "tile_x_link", "tile_link"]
    extra_links: null

    cspace:
      joint_names: [base_to_height_joint, height_to_tile_x_joint, tile_x_to_tile_y_joint]      
      retract_config: [0.0, 0.0, 0.0]
      null_space_weight: [1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 20.0
```

#### `output in terminal`
```
>>> IK Result Success:  tensor([[False]], device='cuda:0')
>>> IK Result:  IKResult(js_solution=JointState(position=tensor([[[nan, nan, nan]]], device='cuda:0'), velocity=None, acceleration=None, joint_names=['base_to_height_joint', 'height_to_tile_x_joint', 'tile_x_to_tile_y_joint'], jerk=None, tensor_args=TensorDeviceType(device=device(type='cuda', index=0), dtype=torch.float32, collision_geometry_dtype=torch.float32, collision_gradient_dtype=torch.float32, collision_distance_dtype=torch.float32), aux_data={}), goal_pose=Pose(position=tensor([[15., 15.,  1.]], device='cuda:0'), quaternion=tensor([[1., -0., -0., -0.]], device='cuda:0'), rotation=None, batch=1, n_goalset=1, name='ee_link', normalize_rotation=True), solution=tensor([[[nan, nan, nan]]], device='cuda:0'), seed=None, success=tensor([[False]], device='cuda:0'), position_error=tensor([[nan]], device='cuda:0'), rotation_error=tensor([[nan]], device='cuda:0'), error=tensor([[nan]], device='cuda:0'), solve_time=0.0068471431732177734, debug_info={'solver': {'steps': [[], []], 'cost': [[], []]}}, goalset_index=tensor([[0]], device='cuda:0', dtype=torch.int32))
>>> Trajectory Generated:  tensor([False], device='cuda:0')
```
